### ISSUE TITLE
updating to beta causes loss of privileges

### ISSUE THREAD

**Issue by jt196** [vabene1111/recipes#523] opened 2021-04-05 17:36 UTC
### Version
On update from 0.14.5 to the beta (0.15) as of about 12pm today in Docker. 
Version: 

### Bug description
Get a warning message on front page saying user isn't part of a group, so can't do anything. 

I solved this by going into the user > admin > users > my user, assigning a group and rights to the user as the user had none of either after the update.

**Comment by vabene1111** [comment] 2021-04-05 20:13
that is actually expected behavior as a user always needs to have some kind of group (guest, user or admin) to work properly.

Did you use that user before the update ? Because it should not have been usable except maybe if it was a superuser ...

**Comment by jonahwh** [comment] 2021-04-05 20:14
This happened to me with my superuser account as well. I had to assign it the "user" group via the admin UI in order to access the site again.

**Comment by vabene1111** [comment] 2021-04-05 20:17
yea this is a little dumb as superusers created with the old/manual setup dont have any groups .. i will see if i can add a little piece of code that automatically assigns superusers a group

**Comment by jt196** [comment] 2021-04-06 08:37
It was the main user on the system. So pre-upgrade, everything worked fine, afterwards, user wasn't in any groups and lacked permissions.

**Comment by vabene1111** [comment] 2021-04-06 16:12
fixed this in 0.15.1. A default group (admin) is assigned to each existing superuser. This is only required for older installations as the newer ones add the groups automatically when creating the first user during the initial setup

**Closed by vabene1111** 2021-04-06 16:12 UTC

**Comment by IxsharpxI** [comment] 2021-04-06 17:02
been watching my logs for watchtower and it hasnt pulled the new image yet. im currently locked out of everything. looks like the fix is made. How long does it take to be available?

**Comment by MaxJa4** [comment] 2021-04-06 17:29
Just some more minutes, building needs some time.

You can check at: https://github.com/vabene1111/recipes/actions/runs/723157207

**Comment by jt196** [comment] 2021-04-06 17:58
> been watching my logs for watchtower and it hasnt pulled the new image yet. im currently locked out of everything. looks like the fix is made. How long does it take to be available?

Follow the steps I outlined in the original post. You just check a box in the admin area.

**Comment by vabene1111** [comment] 2021-04-06 19:48
Yea the build is extremly slow because libxml takes forever and the images are build for many architectures

@IxsharpxI you should have a superuser account which can assign groups to all users. If not i can help you restore it if needed
