### ISSUE TITLE
Error Saving A Recipe

### ISSUE THREAD

**Issue by cowenby** [vabene1111/recipes#138] opened 2020-07-17 02:33 UTC
### Version
Version: 0.10.0

### Bug description
Upon saving a recipe, I get the follow error. It does not happen to all recipes, just one. I don't have any duplicate food items, which is the error appears to be referencing. 
`There was an error updating the recipe!{"steps":[{"ingredients":[{},{"food":{"name":["This field must be unique."]}},{},{},{},{},{},{},{}]}]}`

**Comment by vabene1111** [comment] 2020-07-17 07:03
That is very interesting. The error occurs because of the nested serializers not recognizing that a food already exists but i put some additional methods in that verify that no object gets created that already exists 🤔 

Is the recipe a new recipe added after 0.10 released or was it there before and ran trough the migrations ?

I would be awesome if you could provide an export of the recipe (trough the export function) or screenshots if the export is broken as well so that i can take a look at the data.

You could also (and that would be very interesting to debug this) open the browser dev tools and type `app.recipe` and post the resulting object here.

Sry for the inconvenience, this is probably some edge case is missed ...

**Comment by cowenby** [comment] 2020-07-17 13:47
It is happening to recipes that were created before and created after 0.10. It does not affect all recipes though. (I was adding a keyword when I found an old one that wouldn't save.) 

[Imported in V0.9.2 Instant Pot Chicken and Dumplings.txt](https://github.com/vabene1111/recipes/files/4938127/Imported.in.V0.9.2.Instant.Pot.Chicken.and.Dumplings.txt)

[Imported in V0.10.0 DIY TACO SEASONING RECIPE.txt](https://github.com/vabene1111/recipes/files/4938138/Imported.in.V0.10.0.DIY.TACO.SEASONING.RECIPE.txt)

**Comment by cowenby** [comment] 2020-07-17 13:59
Here are the outputs from Debug Tools:

[Debug Tools Output - Instant Pot Chicken and Dumplings.txt](https://github.com/vabene1111/recipes/files/4938190/Debug.Tools.Output.-.Instant.Pot.Chicken.and.Dumplings.txt)
[Debug Tools Output - TACO SEASONING RECIPE.txt](https://github.com/vabene1111/recipes/files/4938191/Debug.Tools.Output.-.TACO.SEASONING.RECIPE.txt)

**Comment by cowenby** [comment] 2020-07-17 14:37
And don't worry about the inconvenience. :) I fully understand/understood what I was getting into. 

You have been very responsive and helpful, which is the best I could hope for. 
 
The positives far outweigh these little things: 
1.  The clean interface and simplicity of it.  
1. It doesn't rely on a specific ecosystem and will works with anything that has a web browser.  
1. It shouldn't require changes to work with newer os's.  
1. There are ways to back it up and export the recipes, (I go the DockerPostgresBackups working to run a backup.)  
2. I am not reliant someone else's cloud services.  
1. It's inexpensive.

**Comment by cowenby** [comment] 2020-07-18 12:54
Had an epiphany this morning lying in bed. You mentioned adding some more checks in there, so I took a look at my ingredients list. Turns out I had "Salt" in there twice. One I merged them, the issues have gone away.

**Comment by cowenby** [comment] 2020-07-18 13:02
Which now makes me wonder, Is there a way to rebuild the ingredient list from scratch?

**Comment by cowenby** [comment] 2020-07-18 13:43
I thought it was fixed, but it's not. I do have more information though:
When using website import, it apparently doesn't grab the ingredient reference so it creates another one even though their is already one existing.

**Comment by vabene1111** [comment] 2020-07-20 12:49
Thats awesome, thanks for all the debugging. I should probably be able to reproduce this now and when i do i can fix the bug and add a migration that merges all duplicate foods/units/ingredients. I hope i can get this figured out today, otherwise it might be until Wednesday

**Comment by vabene1111** [comment] 2020-07-20 19:47
Ok so i have been investigating this issue further and cannot find a way to reproduce it (except when importing recipes with ids which should not happen since ID's are not exported [but i have added a secondary check to make sure they aren't]). 

What is really interesting to me is that you say that you had the same food twice with different IDs. This should be impossible since there is a unique check on the name field on database table. Are you 100% sure that you `Salt` twice with different ID's ? If this is the case there would be some kind of bug (possibly in a transaction) that allowed the database to skip the uniqueness check and create a food twice. I tried every method i could think of and was not able to duplicate a food.

Just to avoid confusion: The naming for units, ingredients and foods has changed as of 0.10.0. Before it was Recipes with recipe ingredients wich consisted of units and ingredients. Due to the ambiguous use of ingredient i renamed it to Ingredients having a food and unit (along with some other fields).

I restored an old database backup from 0.9.0 and imported both recipes, then upgraded to 0.10.0 and was able to edit the recipes without problems. What Database are you running ?  What browser are you using (this should not make a difference but i am kinda running out of ideas what might be causing this) ? 

Last resort would be for you to send me a database dump which i could use to replicate the issue. You can create one using `docker-compose exec db_recipes pg_dumpall -U djangodb > "dump.sql` (if you are using the standard setup). **Do note** however that this dump will contain the tokens/passwords if you use external storage and also all usernames/password hashes and valid sessions. You either have to remove them from the dump or send it to me via email (vabene1234@googlemail.com) or do both. Sry for bothering you so much with this but i just cannot reproduce the issue, not even when purposely manipulating data in the database.

**Comment by cowenby** [comment] 2020-07-21 03:08
1. It appears that the conflict may originate form some items have a space before the ingredient? But that seem kinda odd. I just emailed the dump over. ( I don't have any external storage) Its chrome on android and windows.
2. Also, I have another one that wont import but should. I think the issue with this one is that it is trying to find an image but none-exists: https://practicallyhomemade.com/kentucky-butter-cake-cookies/
3. Last item, I am getting the attached error when I edit the units in the website import. Doesn't happen on any other pages though. 
[192.168.86.2-1595300486987.log](https://github.com/vabene1111/recipes/files/4951070/192.168.86.2-1595300486987.log)

**Comment by cowenby** [comment] 2020-07-21 03:08
Maybe I just need to do a backup of the database, do a clean install and then restore the back-up?

**Comment by vabene1111** [comment] 2020-07-21 05:09
that might help, let me test it (in the evening) and i will get back to you if you dump works on me. If find it quite unlikely (and unsatisfying) that a database corruption is the cause of this problem but even tough there are many safeguards in place that should prevent something like this its probably not impossible.

Thanks for or all the help debugging this, i will get back to you asap.

**Comment by vabene1111** [comment] 2020-07-21 19:57
Ok so i have setup a test system with your database dump and i can view and save every recipe i tried. I also looked at the raw database dump itself and it does not seem like anything is wrong here. 

This is very weird and concerning as i do not believe that some kind of setup error caused this issue. You can most likely fix it by dumping and loading the database again. If you want to do one other thing before you can send me an archive of the `postgresql` folder. The reason for this is that if i load the entire folder i should have an 100% identical copy of you DB while loading the dump might correct the error that caused it in the first place (sorry for not thinking of this earlier).

To restore the databse you can use `docker-compose exec -T "db_recipes" psql -U "djangodb" postgres < "dump.sql"` (use the previously posted command to generate the dump). This should hopefully fix the issue for you i hope.

**Comment by cowenby** [comment] 2020-08-07 19:32
I know it has been a while, but I backed up the PostgreSQL using your PostgreSQL backup script and had some issues back and forth on that, but I was just poking around and it is working today, so I really am beginning to think it is a setup issue on my end. I'm gonna try to rebuild it from scratch this weekend and see how it goes. Are there any tricks importing the database back into a new install?

**Comment by vabene1111** [comment] 2020-08-08 17:49
it shouldn't be anything more than running the restore script to load the database back in. You probably need to delete the old `postgresql` folder first and then run the restore script. Sometimes docker/the restore behaves a little weird so running the script twice might be necessary.

Please let me know if you can figure out whats wrong, if you need any additional help feel free to ask.

**Comment by vabene1111** [comment] 2020-09-21 21:23
Closing as this appears to be resolved and not happending for any other users

**Closed by vabene1111** 2020-09-21 21:23 UTC
Labels: bug, edge case, setup issue
