### ISSUE TITLE
Import from rewe.de not working

### ISSUE THREAD

**Issue by frudolph77** [vabene1111/recipes#439] opened 2021-02-20 21:45 UTC
**Is your feature request related to a problem? Please describe.**
I've tried to import a recipe from [rewe.de](https://www.rewe.de/rezepte) the import is not working, nothing is imported and I got an error page.

**Describe the solution you'd like**
Imported recipe :-)

**Describe alternatives you've considered**
Add recipe by hand. :-)

**Additional context**
I've quick read the linked page about Google ld+json Info. There was a link inside the page to [Test für Rich-Suchergebnisse](https://search.google.com/test/rich-results) there i've pasted a link to a recipe on the rewe.de.

See the [result](https://search.google.com/test/rich-results?id=lS5wlBZ4YhURCKXZmLKd5A) the page contains all relevant information, have also seen them in the source of the page.

**Comment by vabene1111** [comment] 2021-02-20 21:55
as far as i remember the problem with rewe.de was that they have the data but are very fast to block requests from datacenters and with useragents they dislike. There was another issue were we discussed that changing the user agent might help for a different problem so maybe this fixes this as well

**Comment by sebimarkgraf** [comment] 2021-03-18 19:24
I found the issue.

The request ends in the bot protection of rewe.de.
They are doing one of two things:
* Checking if our parameters are off (User-Agent, Accepts, ... needs tuning)
* Executing javascript to test if we are a real browser 
If the second option is true, we maybe need to change to something like https://pypi.org/project/requests-html/ to circumvent the protection.

I am going to check tomorrow if other user-agents help on more webpages. Maybe, using the exact parameters of a default Chrome / Windows 10 Browser would be harder to detect. Just due to the sheer number of users that probably have that combination.

**Comment by vabene1111** [comment] 2021-03-18 19:27
thanks for investigating, there are also other pages which might be broken due to their useragent so changing that and testing if it works better might help

**Comment by sebimarkgraf** [comment] 2021-03-18 20:50
Rewe.de seems to use cloudflare for their protection. They are currently using JS to verify it's a real person and not a scraper.
Therefore, changing the user-agent won't help at all.

I don't think bypassing captchas should be in the scope of this project, as this effort is continuous and takes a lot of time.
One possible solution is to rely on libraries that try to solve it, e.g. https://github.com/VeNoMouS/cloudscraper
Another solution is to declare these pages as not parsable from the server-side and rely on a manual process to somehow get the JSON.

**Comment by vabene1111** [comment] 2021-03-18 21:37
I think the last solution is the way to go. If a website does not want to be parsed we should not parse it. Just from a legal standpoint probably the best option.

So i am closing this and with that declaring rewe.de not parsable.

More interesting is that there seem to be a few pages which allow the json to load but not the images but this might also be related to the cdn (even tough i could never reproduce the issue)

**Comment by vabene1111** [comment] 2021-03-18 21:38
Also with the next update it is possible to manually import ld+json so one could technically extract it from the pages source code or a small browser extension could be used to do so

**Closed by vabene1111** 2021-03-18 21:37 UTC
Labels: enhancement, url import
