### ISSUE TITLE
Importing recipes with Fraction units mangles the parsing.

### ISSUE THREAD

**Issue by callingshotgun** [vabene1111/recipes#216] opened 2020-11-03 20:12 UTC
### Version
0.11.0

### Bug description
- Import recipe from URL.  Example URL : https://justcook.butcherbox.com/cuts/beef/flat-iron-steak/
- Source URL has, as an ingredient (in raw JSON) : "\u00bc c olive oil". (html escaped 1/4 c olive oil)
- On imported page, the 3 fields should show:
| 0.25 | c | olive oil |

- However, what shows up is:
| 0 | c | 1/4 c olive oil |

Which is a bit annoying, because  the "ingredient name" field fights me and undoes any edits I make to that field if I tab away instead of hitting enter, and I have to change the same two fields for a several ingredients in the recipe.

Manually detecting some of these fractions (or finding a python library that'll do it for you) and just replacing them with a decimal value so everything else slots in correctly would be hugely helpful.

**Comment by FunWithUrban** [comment] 2020-11-03 21:56
This issue has been discussed in this thread and the developer has pinned it as a top priority. https://github.com/vabene1111/recipes/issues/142

**Comment by vabene1111** [comment] 2020-11-03 22:41
yea ingredient parsing is definitly a big thing. thanks @FunWithUrban for mentioning the other issue but i guess this is another thing that is not really that prominent in the other one. 

I will take a look at this to build some decimal conversions.

**Comment by vabene1111** [comment] 2020-12-14 18:55
ok so i have fixed this specific recipe that uses unicode fractions to display floats. This does not work for recipes containing improper fractions (i.e. 1  ¼) and all fractions that are just written with a normal slash. I will close this issue but if you run into examples of recipes using other common formats feel free to open new issues with them.

The problem is that every page does their own stupid thing (even with decimals) and fractions just makes it more annoying because everything needs to be another path in the parser. This always only works with examples.

**Closed by vabene1111** 2020-12-14 18:55 UTC
Labels: bug
