### ISSUE TITLE
Recipe notes not popping up

### ISSUE THREAD

**Issue by HunterMorrell** [vabene1111/recipes#144] opened 2020-07-29 19:57 UTC
Version: 0.10.0

When clicking the "i" button beside recipe ingredient entries, nothing happens. 

I've tested this on:
- Desktop: Firefox (v78.0.2), Chrome (v84.0.4147.89), and Edge (v44.18362.449.0)
- Mobile: Firefox (v68.11.0)

While both Firefox installs do have ad blocking and JavaScript blocking, neither Chrome nor Edge do. The activity seems to be replicated on all of them, so I don't think it's a browser issue. I am running PiHole, but I don't see any blocked requests in the admin interface, so I doubt that it's a network wide issue either.

When viewing the element in Inspector node, the bit of code that contains the note is greyed out, though that might just be because it's technically not "active" yet. I don't know enough about web dev to say one way or another.
![image](https://user-images.githubusercontent.com/50470626/88843989-fbab2200-d1af-11ea-8ab4-d71e56e7fb5c.png)

Also in Inspector mode, there are two warnings the accompany the page load, about Source Mapping:
![image](https://user-images.githubusercontent.com/50470626/88844054-154c6980-d1b0-11ea-98c5-fc0c9782d7e8.png)

When viewing the logs via `docker-compose logs -f`, the only things of note that I see is warning about "upstream response is buffered":
![image](https://user-images.githubusercontent.com/50470626/88844235-5e9cb900-d1b0-11ea-8e59-7399a0a2331a.png)

I am using the plain config. The only alterations that I have made (beyond something like SECRET_KEY) are to change the external port that the nginx_recipes is exposed on. 

I can reach the site just fine and all other functionality -seems- to work. I've already looked through a previous issue that was opened about this, which is [here](https://github.com/vabene1111/recipes/issues/98) but I don't believe that the cause is the same. Via that issue, I also found the [popover information page](https://getbootstrap.com/docs/4.5/components/popovers/) and was able to successfully get those buttons working and see the popover. 

One last thing to mention is that there was an error upon starting up the nginx_recipes container, though I'm not sure of the relevance:
![image](https://user-images.githubusercontent.com/50470626/88845829-bb00d800-d1b2-11ea-8e48-eb2bc6b6a0e5.png)

I've attempted to update that line in `nginx/conf.d/Recipes.conf` to use 
- the name listed under `docker-compose ps` which is `recipes_web_recipes_1`
- the name listed in `docker-compose logs -f` which is `web_recipes_1`
Neither of which worked. The first one had the same behavior as just `web_recipes`, which is to say it gave that error but continued fine. Using the second broke everything entirely and the nginx container just repeatedly tried it, gave the error, and eventually just exited entirely. 

This is definitely a low priority issue, so I appreciate any help in getting this figured out!

**Comment by vabene1111** [comment] 2020-08-08 17:55
sry for not responding to this for so long, i am extremly busy right now, i will try to get back to you as soon as possible. Also thanks for the very detailed report!

**Comment by jessecureton** [comment] 2020-08-09 18:13
Hi! Just wanted to weigh in that I'm experiencing the same issue with recipe notes not appearing. It does not occur in `0.9.2` but does in `0.10.0`.

Tested browser versions, each on macOS:

    - Firefox - 78.0.1
    - Chrome - 84.0.4147.105
    - Safari - 13.1.1 (15609.2.9.1.2)

This occurs in both a local build running on my Mac with `docker-compose up -d` using the "plain" compose config, as well as running on a Hashicorp Nomad cluster with Linux nodes. The Nomad deployment is based on the k8s demo config in the repo.

**Comment by vabene1111** [comment] 2020-08-09 18:27
it appears that this was caused by the migration of the recipe view page to vue. Its fixed in the upcoming release.

**Closed by vabene1111** 2020-08-09 18:27 UTC
Labels: edge case, setup issue

**Comment by vabene1111** [comment] 2020-08-09 19:19
update is released
