### ISSUE TITLE
Ingredient notes won't show

### ISSUE THREAD

**Issue by therealschimmi** [vabene1111/recipes#98] opened 2020-06-04 19:17 UTC
When adding notes to ingredients i get the little info box on the recipe page. How is that supposed to work? Neither hovering nor clicking will make the note appear.

**Comment by vabene1111** [comment] 2020-06-04 19:56
are you running the latest version (0.8.2) ? i broke tooltips in 0.8.0 and fixed it yesterday evening in 0.8.2

**Comment by therealschimmi** [comment] 2020-06-09 07:33
how do i check?

**Comment by vabene1111** [comment] 2020-06-09 10:29
currently there is no integrated version info, best would be to just do a update (docker compose down, pull, up -d)

**Comment by vabene1111** [comment] 2020-06-09 10:30
showing the version will be added probably with the next release

**Comment by therealschimmi** [comment] 2020-06-09 18:34
ok, but how do I backup the my recipes before the update? They will be lost if I update, right? My understanding is the dropbox/nextcloud thing just works for importing recipes?

**Comment by therealschimmi** [comment] 2020-06-09 18:36
btw: if i try deleting a storage location and there's still a monitored folder pointing to that, i will get a cryptic looking error page

**Comment by vabene1111** [comment] 2020-06-09 22:44
the last one is definitly an issue i will need to fix. Normally no data should be lost during any updates, backups are just for security reasons. Just copy you `postgresql` folder or dump the database using `pg_dumpall`

**Comment by vabene1111** [comment] 2020-06-09 22:45
i opened a new issue for the monitor/storage problem #102 102

**Comment by therealschimmi** [comment] 2020-06-10 05:44
I don't have a postgresql folder, pg_dumpall: not found
what I have is a db.sqlite3 file?
i'm running this on a Synology NAS from your docker container, should be the 0.7.1 release

**Comment by therealschimmi** [comment] 2020-06-10 06:00
#96 seems to be related... wouldn't it be possible to store the recipe data in a mapped folder? other containers do exactly that, all the important stuff is very accessible and persistant if you delete the container or chose to run it in a different configuration

**Comment by vabene1111** [comment] 2020-06-10 07:37
i do exactly that if you follow the recommended setup ... 

Generally running on a sqllite database in production is not recommended but you can certainly do that, you just need to add a mapping for the install folder which included you sqlite fille (something like ./recipes:/opt/recipes). But i strongly recommend you create yourself a second container running postgres and use that as the database.

**Comment by therealschimmi** [comment] 2020-06-10 09:20
apaprently through the synology docker gui i got the container running without proper nginx and postgres containers. Want to try a clean install through CLI, this is what I get
![grafik](https://user-images.githubusercontent.com/66269214/84250414-51e2d980-ab0c-11ea-9749-4b4f4b082c4e.png)
where do i get conf.d?

**Comment by vabene1111** [comment] 2020-06-10 09:35
you need to download the nginx folder from the docs examples https://github.com/vabene1111/recipes/tree/develop/docs/docker/plain

**Comment by therealschimmi** [comment] 2020-06-11 06:13
great, finally got 0.8.3 set up correctly with all three containers running instead of just one. Thank you very much!
now i imported a recipe through the json import feature. It still wont show the tooltips. Even when I create a new recipe from scratch, same effect.
btw: i did an update to 0.8.4 right now through CLI: down, pull, up -d...the docker-hub page says to to update.sh on each update. is that still required? how and where do i do that?

**Comment by vabene1111** [comment] 2020-06-11 06:55
oh i guess docker hubs description is outdated, i will fix that. Running update.sh should never be required (you should not even have a update.sh if you are running the image version), at least not on the host system. 

I have one idea, maybe the static files aren't collected (for whatever reason) so you could actually try  executing into the container (docker-compose exec web_recipes sh) and run update.sh manually to see its output. 

Other than that you can post your Browser/Version, the output of `docker-compose logs -f` (this might be pretty big, in that case down&up the container, open the recipe page once and then post it). Also the Browser dev tools console output might be interesting since this is most likely a javascript errror.

**Comment by therealschimmi** [comment] 2020-06-11 07:09
![grafik](https://user-images.githubusercontent.com/66269214/84355048-3e924580-abc2-11ea-82c0-a91bf1deca3f.png)
no update.sh :(

![grafik](https://user-images.githubusercontent.com/66269214/84355443-ead42c00-abc2-11ea-99cd-82c0a4940791.png)
also no logs.

Firefox 76.0.1 on MacOS

**Comment by vabene1111** [comment] 2020-06-11 08:35
oh i forgot, its now the `boot.sh` that does what the update.sh used to do.

please run 
`python3 manage.py collectstatic  --noinput` inside the container. Also please open the page in firefox and hit `F12` to open the debug tools (there should be a tab called console) and send me the errors if there are any.

**Comment by koch17** [comment] 2020-06-12 00:26
Hi therealschimmi,
It looks like you were able to make work something I struggle with for two weeks now. Is there any chance you could make a detailed guide of your setup? Me and other synology users would greatly appreciate.

**Comment by therealschimmi** [comment] 2020-06-12 04:49
yes of course I can do that

**Comment by therealschimmi** [comment] 2020-06-12 04:53
vabene1111: the staticfiles and mediafiles folder, shuld it be separate pathsfor nginx and recipes or should it be the same so they can exchange data that way? Might that be related to my tooltip issue?

**Comment by vabene1111** [comment] 2020-06-12 07:20
Thanks for the great guide! As synology hosting seems to be a common thing, would you mind me putting this guide in the "offical" docs ?

Also did you solve your problem by running collectstatic or is it still bugged ?

**Comment by therealschimmi** [comment] 2020-06-12 08:52
Feel free to put the guide to the docs :) happy to help

No, the tooltips still dont work. see below. what does that mean
```
admin@Synology:/volume1/docker/rezepte$ sudo docker-compose exec web_recipes sh
Password: 
/opt/recipes # python3 manage.py collectstatic --noinput
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environmen
```


firefox debug concole
```
10:48:33.310
Fehler beim Verarbeiten des Wertes für '-webkit-text-size-adjust'.  Deklaration ignoriert. flatly.min.f99bb7c874e0.css:12:1000
10:48:33.313 Unbekannte Pseudoklasse oder Pseudoelement 'focus-visible'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:1445
10:48:33.315 Unbekannte Pseudoklasse oder Pseudoelement '-ms-expand'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:30368
10:48:33.315 Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:30753
10:48:33.315 Unbekannte Pseudoklasse oder Pseudoelement '-ms-value'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:30959
10:48:33.319 Unbekannte Pseudoklasse oder Pseudoelement '-ms-value'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:75150
10:48:33.319 Unbekannte Pseudoklasse oder Pseudoelement '-ms-expand'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:75393
10:48:33.319 Unbekannte Pseudoklasse oder Pseudoelement '-ms-thumb'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:77404
10:48:33.319 Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:78334
10:48:33.319 Unbekannte Pseudoklasse oder Pseudoelement '-ms-thumb'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:79527
10:48:33.319 Unbekannte Pseudoklasse oder Pseudoelement '-ms-thumb'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:80230
10:48:33.319 Unbekannte Pseudoklasse oder Pseudoelement '-ms-thumb'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:80296
10:48:33.319 Unbekannte Pseudoklasse oder Pseudoelement '-ms-track'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:80353
10:48:33.319 Unbekannte Pseudoklasse oder Pseudoelement '-ms-fill-lower'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:80510
10:48:33.319 Unbekannte Pseudoklasse oder Pseudoelement '-ms-fill-upper'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:80584
10:48:33.319 Unbekannte Pseudoklasse oder Pseudoelement '-ms-thumb'.  Regelsatz wegen ungültigem Selektor ignoriert. flatly.min.f99bb7c874e0.css:12:80946
10:48:33.321
Unbekannte Eigenschaft 'orphans'.  Deklaration ignoriert. flatly.min.f99bb7c874e0.css:12:96405
10:48:33.321
Unbekannte Eigenschaft 'widows'.  Deklaration ignoriert. flatly.min.f99bb7c874e0.css:12:96414
10:48:33.323
Unbekannte Eigenschaft 'backdrop-filter'.  Deklaration ignoriert. flatly.min.f99bb7c874e0.css:12:113310
10:48:33.327
Unbekannte Eigenschaft 'orphans'.  Deklaration ignoriert. flatly.min.f99bb7c874e0.css:12:179940
10:48:33.327
Unbekannte Eigenschaft 'widows'.  Deklaration ignoriert. flatly.min.f99bb7c874e0.css:12:179949
10:48:33.327 Unbekannte Eigenschaft 'size'.  Deklaration ignoriert. flatly.min.f99bb7c874e0.css:12:179991
10:48:33.372
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. select2.min.9f54e6414f87.css:1:2498
10:48:33.372
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. select2.min.9f54e6414f87.css:1:9061
10:48:33.372
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. select2.min.9f54e6414f87.css:1:10099
10:48:33.372
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. select2.min.9f54e6414f87.css:1:11631
10:48:33.372
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. select2.min.9f54e6414f87.css:1:12150
10:48:33.395 Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. select2-bootstrap.dcec0cc93fba.css:106:54
10:48:33.406 Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. select2-bootstrap-theme.d007f71f4d38.css:106:54
10:48:33.445
Unbekannte Eigenschaft 'print-color-adjust'.  Deklaration ignoriert. pretty-checkbox.min.60e283066a62.css:12:19011
10:49:24.603 onmozfullscreenchange sollte nicht mehr verwendet werden. 7
10:49:24.603 onmozfullscreenerror sollte nicht mehr verwendet werden. 7
10:49:24.621 "get" oder "set" einer Eigenschaft mit [LenientThis] ignoriert, weil das "this"-Objekt fehlerhaft ist. 7
```

​

**Comment by vabene1111** [comment] 2020-06-12 09:29
oh sry, i forgot that the container now runs venv as well, please run the following command again to see what happens

```
source venv/bin/activate
python3 manage.py collectstatic --noinput
```

sry for all the back and forth but i cant reproduce your issue on my end so i have to do it this way. Other than that, if you want, we can use some kind of remote desktop service so that i can take a direct look at what is wrong with the setup (did that once with discord/anydesk when another user had a problem).

**Comment by therealschimmi** [comment] 2020-06-12 09:40
Thats what I get.

```
(venv) /opt/recipes # python3 manage.py collectstatic --noinput

0 static files copied to '/opt/recipes/staticfiles', 655 unmodified, 1248 post-processed.
(venv) /opt/recipes # 
```

**Comment by vabene1111** [comment] 2020-06-12 10:10
hmm that looks like everything is working perfectly fine. Also just tested the tooltips in firefox and everything appears to be working correctly

i am kinda running out of ideas, if you want feelfree to add me on discord and i can try to look at it trough anydesk/teamviewer/whatever but other than that i dont really now how to help you ..

**Comment by koch17** [comment] 2020-06-12 17:00
So many stupid and wrong things I was doing before. Thank you so much therealschimmi, I followed your guide and it now works and thanks vabene for this awesome app. I am just a beginner, but I already love the open source community.

**Comment by therealschimmi** [comment] 2020-06-12 18:52
Soooo... the whole issue seems to be MacOS and iOS related. Tested on a Win7 machine with chrome and firefox and when I click on the "i" symbol the tooltip will show, is that behaviour correct?
At least on my iPhone I found a category of settings called "experimental webkit features", could that be related somehow?

**Comment by vabene1111** [comment] 2020-06-13 11:02
hmm that is interesting. I am using bootstraps default tooltips (https://getbootstrap.com/docs/4.5/components/tooltips/) which i thought would work cross platform. 

Do you have some kind of adblocker that blocks javascript from running ? 

I sadly cannot test on iOS/MacOS since i dont own any apple devices .. but you were using firefox i would think that this would be a browser specific issue that i could also reproduce on windows/linux. Also the browser console output you showed above does not have any errors, usually everything that causes issues with javascript shows in the console ...

**Comment by vabene1111** [comment] 2020-06-13 11:05
If you go to the shopping list page, does a tooltip show when you hover over the copy button ? and do tooltips show when you hover over the little buttons in the recipe view ?
![image](https://user-images.githubusercontent.com/6819595/84567070-7fcb5680-ad76-11ea-88fc-8c2787afaedf.png)

**Comment by vabene1111** [comment] 2020-06-13 11:06
correction, these are tooltips, what isn't working for you are the popovers https://getbootstrap.com/docs/4.5/components/popovers/

**Comment by therealschimmi** [comment] 2020-06-13 11:09
> correction, these are tooltips, what isn't working for you are the popovers https://getbootstrap.com/docs/4.5/components/popovers/

the examples on this website work for me

**Comment by vabene1111** [comment] 2020-06-13 11:12
interesting 🤔 you have the same issue on iOS and on MacOS both with firefox or safari ?

I think i can find an old iPad somewhere to test it out ...

**Comment by therealschimmi** [comment] 2020-06-13 11:19
None of these work:
MacOS: Safari and Firefox
iOS: Chrome, Safari, Opera and Firefox

**Comment by vabene1111** [comment] 2020-06-13 11:19
ok i was able to reproduce the issue in safari on an iphone .. now to find out what causes it.

**Comment by therealschimmi** [comment] 2020-06-13 11:23
thank god...i was beginning to think I was the problem :)

**Comment by vabene1111** [comment] 2020-06-13 11:35
haha i was so sure that this must have been a setup issue that i ignored the fact that it might be something else. very interested to see what causes this because if firefox/chrome on windows works it should work on mac as well

**Comment by vabene1111** [comment] 2020-06-13 12:03
ok if i had read the documentation correctly i would have seen that there is indeed a cross browser support issue with popovers https://getbootstrap.com/docs/4.5/components/popovers/#dismiss-on-next-click

i fixed it, feel free to try out the development branch of the image (note you cant go back to master until i release it then because there are breaking data migrations, the new meal plan is in there).

Just as a rant/note: I really hate apple and this confirms it again. There are literally multi page long tutorials to maybe get some kind of javascript debugging working on their stupid overpriced tech scrap if you dont own one of desktop os machines .. /rant off

**Comment by vabene1111** [comment] 2020-06-13 12:04
updates pushed and will be released as vabene1111/recipes:develop in about 5 minutes ea96c63289fa50a74e597bc4d21f870fc66e0a8b

**Closed by vabene1111** 2020-06-13 12:03 UTC
Labels: bug

**Comment by lidans5** [comment] 2022-02-10 21:20
I'll be great full for some help I followed the pdf guide for my synology (ds220+)
and the "Web Application Container (Tandoor_Web)" keeps stopping and restarting, when "Start the Containers" phase
thx

**Comment by smilerz** [comment] 2022-02-10 21:24
> I'll be great full for some help I followed the pdf guide for my synology (ds220+) and the "Web Application Container (Tandoor_Web)" keeps stopping and restarting, when "Start the Containers" phase thx

please open a new issue providing the necessary setup & log info.  this issue isn't related

**Comment by RemakingEden** [comment] 2022-06-01 08:45
Sorry to bring this thread back from the dead. Feel free to tell me to open a new issue if needs be. 

---

I am still getting this issue on Safari on iOS 

Spec:
iOS 15.5 
iPhone 8. 
4.7-inch (diagonal) widescreen LCD 
1334-by-750-pixel resolution at 326 ppi

Steps to reproduce:
1. Open recipe with notes on the ingredient prep
2. Tap a note speech bubble

Expected:
- Note would be shown as it does on Chrome

Actual:
- Ingredient is checked and no note is shown

Please let me know if you need any more details or a video etc? I'm also available to retest new fixes if you want it testing on the same hardware, thanks.
