### ISSUE TITLE
Add a thumbnail of the meal to Meal Plan

### ISSUE THREAD

**Issue by frudolph77** [vabene1111/recipes#437] opened 2021-02-20 20:47 UTC
**Is your feature request related to a problem? Please describe.**
The very first moment I've seen the Meal Plan, I thought a thumbnail of the meal would be great here.

**Describe the solution you'd like**
Later I've seen the MealPlan in grocy, I like how the Meal Plan is shown there, but only a picture would be ok.

**Describe alternatives you've considered**

**Additional context**
btw. Meal-Plan should be translated as *Speiseplan* in the german version.

**Comment by vabene1111** [comment] 2021-02-20 20:52
thanks for the feedback. A visual rework of the meal plan is definitly on my todo list but i first need to rewrite it to the new vue.js component system. While doing so i will probably also add the thumbnails

**Comment by vabene1111** [comment] 2021-09-04 16:48
closing this as a duplicate of #361

**Closed by vabene1111** 2021-09-04 16:48 UTC
Labels: enhancement
